language: haskell

script:
  - cabal install --only-dependencies && cabal configure && cabal build

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - sudo apt-get update -qq
  - cabal update
  - sudo apt-get install -qq libgsl0-dev liblapack-dev

install:
  - cabal install --only-dependencies
  
notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#hnn"
